### ISSUE TITLE
-3+5 resolves to -8

### ISSUE THREAD

**Issue by clayu** [GeorgDangl/Dangl.Calculator#1]
I think it's evaluating -(3+5) instead of (-3)+5

**Comment by GeorgDangl** [comment]
Hi clayu,

thank you very much for raising this issue! I'll look into it, but it might take me one or two weeks since I'm currently on holiday. I don't get lots of time for coding right now=)

**Comment by GeorgDangl** [comment]
Hey @clayu, seems like it was an easy fix. Version v1.1.1 should be available on NuGet in a few minutes with the bugfix. Could you please verify that the issue is solved on your end and give me feedback?

I'll leave the issue open to do a more thorough investigation after my holiday.
