### ISSUE TITLE
Can't use Dangl.Calculator

### ISSUE THREAD

**Issue by alin-1** [GeorgDangl/Dangl.Calculator#9]
Hi. I'm trying to make a simple calculator app. I used Visual Studio's NuGet to install Dangl.Calculator. After I installed it, I wrote **using Dangl.Calculator** but it's greyed out (not available). I can see Dangl.Calculator on the References category on the Solution Explorer but it still doesn't work. When using the code to calculate I get this error:

`CS0234	The type or namespace name 'Calculate' does not exist in the namespace 'Calculator' (are you missing an assembly reference?`

I'm an amateur programmer, can you help me fix this thing? My project is targeting NET Framework 4.8

**Comment by GeorgDangl** [comment]
Hey @alin-1, sorry for the very late reply!

This does indeed sound a bit like a question not directly for this repository. But, some points:
* Maybe you're using the old *.csproj style, for which you might have to manually download the dependencies after specifying them. If that's the case, maybe try switching to the newer *.csproj format if you're able to (e.g. if this is just a learning project)
* The full class name should be `Dangl.Calculator.Calculator`, so to actually do a calculation you would have to write a statement like `var calcResult = Dangl.Calculator.Calculator.Calculate("1+1");`, or when you add `using Dangl.Calculator;` then just write `Calculator.Calculate("1+1")`;
